#STYLES:
# Meta
# Banner
# Experience
# Summary
# List

#FIELDS
# template -- SPECIAL
# style
# company -- switch to name ???
# location
# title
# start
# end
# list

[Template]
style = "Meta"
template = "bugstyle"
title = "Bug Bugson"

[Personal]
style = "banner"
title = "Bug Bugson"
list = [
"555-555-5555",
"ema@ail.com",
"mywebsite.site"
]

[Summary]
style = "summary"
list = [
"This is a summary of myself. This summary takes the form of a short paragraph that will go over relevant interests and skillsets. This can be used as a sort of \"elevator pitch\" for oneself, and should provide an overview of what one can do."]

[Education]
style = "experience"
company = "University of Bug at Bugzone"
#location = "University of Bug at Bugzone"
title = "BS in Entymology"
start = 2015
end = 2019
list = [
"This is a collection of highlights",
"it is a list",
"and it is here"
]

[Experience.1]
style = "experience"
company = "Bug enterprise, inc"
location = "New York, New York"
title = "Engineer Team Lead"
start = "August 2021"
end = "Present"
list = [
"Lead and worked alongside a team of engineers in development of bugware",
"Performed rigorous QA on developed software",
"Met with stakeholders to ensure vision aligned with longterm goals of the project"
]

[Experience.2]
style = "experience"
company = "Bugzone Department of Entymology"
location = "Bugzone, USA"
title = "Arachnid Fulfillment Intern"
start = "September 2017"
end = "August 2019"
list = [
"Tracked the distribution of various arachnid species across local environment",
"Drafted measures for preservation of threatened species",
"Bit so many times that I developed an immunity to various neurotoxins"
]

[Projects]
style = "list"
company = "Resu-Me Resume Parser"
location = "Lead Developer"
title = "https://gitlab.com/bigbookofbug/resu-me"
end = 2023
list = [
"\\textbf{Resu-Me Resume Parser} lead developer \\hfill 2024"
]

[Skills]
style = "list"
list = [
"Proficient in GNU/Linux operating system installation and maintenance.",
"Understanding and enjoyment of the C and Clojure programming languages.",
"Experience with catching and releasing spiders instead of squishing them.",
"Proficient working both alone and in a team-oriented environment."
]


